### ISSUE TITLE
NullPointerException when shutting down the server

### ISSUE THREAD

**Issue by serpi90** [GotoFinal/AutoIn#13]
Sometimes, when shutting down the server, the following error happens.
```
[13:12:43 INFO]: [AutoIn] Disabling AutoIn v3.0-pre.4
[13:12:43 ERROR]: Error occurred while disabling AutoIn v3.0-pre.4 (Is it up to date?)
java.lang.NullPointerException
        at nul.goto. ...\\.. .final..do.for(AutoIn_GotoFinal) ~[?:?]
        at com.gmail.bartlomiejkmazur.autoin.core.server.bukkit.AutoIn.onDisable(AutoIn_GotoFinal) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[spigot-1.8.jar:git-Spigot-b1e6da1-1092acb]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:359) [spigot-1.8.jar:git-Spigot-b1e6da1-1092acb]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [spigot-1.8.jar:git-Spigot-b1e6da1-1092acb]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417) [spigot-1.8.jar:git-Spigot-b1e6da1-1092acb]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.disablePlugins(CraftServer.java:334) [spigot-1.8.jar:git-Spigot-b1e6da1-1092acb]
        at net.minecraft.server.v1_8_R1.MinecraftServer.stop(MinecraftServer.java:430) [spigot-1.8.jar:git-Spigot-b1e6da1-1092acb]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:561) [spigot-1.8.jar:git-Spigot-b1e6da1-1092acb]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]
```

The database only contains one premium player. Which was logged in when shutting down. (test server).
This is the current plugin configuration.

```
# Auto-In 3.0 by GoToFinal! Now with bungee and potatos!
# Plugin website: http://www.spigotmc.org/resources/auto-in.578/
# Issues/bugs, ideas, wiki, api on github: https://github.com/GotoFinal/AutoIn
# |
# You like this plugin? You can support me by donate: (USD) https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=UAAQ6D5CU2F5L
# More donate links in PLN, GBP or EUR you can find here: http://www.spigotmc.org/resources/auto-in.578/
# You can find my other plugins here: http://www.spigotmc.org/resources/authors/gotofinal.31682/
# I also creating plugins "for request" ($), Skype: gotofinal, e-mail: GotoFinalDev@Gmail.com
# |
# If you want use this plugin with bungee vist wiki: https://github.com/GotoFinal/AutoIn/wiki/Bungee-Cord
# Don't change options if you don't understand them -> ask.
# Note: proxy = BungeeCord (or other supported proxy server), Server = Bukkit/Cauldron/Forge/Spigot server.

Sockets: # If you want use this plugin with proxy server (BungeeCord) see: https://github.com/GotoFinal/AutoIn/wiki/Sockets
- TYPE: LISTENER
  Enabled: false
  Host: localhost
  Port: 22644
  ServerName: serverOne
  Required: true
- TYPE: HANDLER
  Enabled: false
  Port: 22644 
# OPTIONS 
Options:
  ConfigurationVersion_DO_NOT_CHANGE_THIS: 1
  UseChannels: false
# DON'T USE THAT IF YOU CAN USE SOCKETS, Enable when you can't use sockets but you want use that on bungee server, it isn't good as sockets, but it should not explode.
# NOTE: You NEED MySQL for that, and this is slower and may by VERY buggy on first join.
  ReTryConnectSocketTime: 250
# Time in ms between trying connect LISTENER to HANLDER socket, on linux using smaller times can cause some weird problems.
  SaveData:
# where AutoIn should store exceptions, enabled login, whitelists, cache and other player settings.
    Type: MySQL 
    MySQL:
      Host: localhost
      Port: 3306
      User: secret
      Pass: secret
      Database: secret
      Prefix: "GT_"
    SQLite:
      File: "AutoIn_PlayerOptions.db" 
  Both:
# options that can be used by proxy and server plugin.
# NOTE: Options are only relevant for the first server which connects to the player. See wiki: https://github.com/GotoFinal/AutoIn/wiki/Player-Connection 
    Dependencies:
      ForceDisable:
# If you have one of that plugin, you can force AutoIn to don't use them even if they can be used. (change to true)
        ProtocolLib: false
        Skript: false
        AuthMe: false
        LogIt: false
        XAuth: false 
    Listeners:
      GetFromModule: true
# you can try disable that and manualy configure priority below if auto-login will stop work after update of auth pluhin. PS: tell me about that problem!
      PlayerLoginEvent: LOWEST
      PlayerJoinEvent: LOWEST
      PlayerQuitEvent: MONITOR
    Players:
      AutoLogin: true
# no more /login commands for premium users! Enable only on servers where you have auth plugin!
      Registration: true
# if true, then even premium players needs to register. PS: You can make registration optional, see wiki: https://github.com/GotoFinal/AutoIn/wiki/Registration
      AllowNewCrackedPlayers: true
# A.K.A. SwitchMode, If you disable that, only old cracked players will be able to join. New cracked players will be kicked from server. Good if you want switch from offline-mode to online-mode without losing players!
      FixedUUID: false
# if true, then everyone have UUID generated from nickname
      CrackedWhiteListEnabled: true
# WhiteList that works only on cracked players, black-list works even if this is disabled.
      Sessions:
        Enabled: true
# If enabled, plugin will remember premium players with their IP number, when servers will be down, premium players can be still auto-logged if IP will be valid.
        AsServerProtect: false
# If true, then players with valid session can join even if mojang server are down and without using password.
#PS: You can enable this and ServerProtect, then registered players OR players with valid session can join.
        Expires: 1d
# time in easy format, 1w = 1 week, 1d = 1 day, 1d5h12s -> 1 day, 5 hours, 12 seconds
        ExpiresOnRestart: true
# If true sessions aren't saved on reload.  
      Protections:
        CrackedPlayersNicknames:
# If enabled, when new cracked player join to game he will get special protection "flag", that work like exception-player. so even if someone buy premium account with this same nickname, he will be still tract as cracked player.
# If player will buy premium, he must disable protection using "IamNowPremium" command, or admin must disable it manually, using API or /setProtection command.
          Enabled: true
          AutoProtect: true
# If disabled, player must use "ProtectMe" command, or protection must be enabled manually, using API or /setProtection command 
# ===================================================================================
# -> NOT IMPLEMENTED YET <-  Options below that comment are -> NOT IMPLEMENTED YET <-
# ===================================================================================
# TODO: Implement.  
        PremiumPlayersUUIDs:
# If enabled and you have also enabled "FixedUUID", then when premium player change nickname, he will still have old UUID, and old nickname will be banned. (becouse someone will have this same UUID as premium player)
          Enabled: true
          Ban: true
# If you disable that, then old nickname will not get ban, so if someone use old nickname he will have this same UUID as premium player. (It's not good, but you can then try option below)
          GenerateNewUUID: false
# If enabled, OLD nickname will be saved to special database, and if someone will use that nickname, then he will get other UUID.
        PremiumPlayersUUIDsConvert:
# If you are more advanced, you can enable "PremiumPlayersUUIDsConvert" option instead of PremiumPlayersUUIDs.
# This option allow you to run command (to server console, and to system, like running .sh scripts), if you enable it, you MUST use it to convert all data from old UUID to new UUID, so premium player will get new UUID to new nickname.
          Enabled: true
          CommandLine:
# NATIVE -> command that will be sent to system. # GAME -> command that will be sent to minecraft server.
# You can use 4 variables here: {oldNickname}, {newNickname}, {oldUUID}, {newUUID}
          - "NATIVE -> ..."
          - "GAME -> ..."
        Bots:
# Bot protection, it's implemented (not yet!) in special module, so you need enable that to start collecting data needed to use it.
          Enabled: true
# when enabled it's starting collection some data (if option below is disabled) Collected data: time of play, destroyed blocks, placed blocks
          UseStats: false
# If enabled, plugin will try use minecraft statistic system to get data. (Don't work on older versions of MC)
          MaxNewPlayersPer10Seconds: 5
# Max new player per 10 seconds.
          NotNewWhen:
            PlayTime: 10m
# player must play longer than 10 mins to be mark as "old", if not using stats, only time when logged-in using Auth plugin is counted (Not work with xAuth, because of bad API).
            DestroyedBlocks: 10
# And dig 10 blocks.
            PlacedBlocks: 5
# And place 5 blocks.
# ===================================================================================
# -> NOT IMPLEMENTED YET <-  Options above that comment are -> NOT IMPLEMENTED YET <-
# ===================================================================================
    ServerProtect:
      Enabled: true
# If enabled and mojang server don't work, only registered players can join (So you must set "Registration" to true). If disabled, all players will be kicked.  
    Cache: true 
# If enabled plugin will remember if username was premium. (It's saved to database/file)
# NOTE: Enable that if you have bigger server, like 100/200+ players online.
  Server: {}
# ignored by proxy plugin. Empty for now...
  Proxy:
# ignored by server
    ForcedServers:
# players from selected group can be send to other servers. This override Proxy/BungeeCord setting!
      PREMIUM:
        Enabled: false
        Server: "PremiumServer"
# works like "default_server" from bungee
        Force: false
# works like "force_default_server" from bungee
        ForcedHosts:
# works like "forced_hosts" from bungee -> this override "Force" option
          'eg.gotofinal.some.network.host.net': "CrackedServer"
        Fallback: "FallbackServer"
# like "fallback_server" from bungee
      CRACKED:
        Enabled: false
        Server: "CrackedServer"
        Force: false
      EXCEPTION:
        Enabled: false
        Parent: CRACKED
# Players with Exception status will use this same settings as Cracked players.
        Force: true
# but you can add options to override them from parent.
      ERROR:
        Enabled: false
        Server: "ErrorServer"
```

**Comment by GotoFinal** [comment]
"The database only contains one premium player."
Are you sure that you have updated database? After one of updates you need use `ai fix 1` command, or just remove DB.

**Comment by serpi90** [comment]
I had updated the database, but i did it again just to be sure, i'll reopen the issue if this happens again.

**Comment by serpi90** [comment]
This happened again, i was testing the plugin configuration before moving it to the real server and when shutting the server down (whitout any connected players) the *NPE* appears again.

The database was fixed last time, so it was not that.

I'm almost sure it's not dangerous, but i would like to know the cause.

**Log**
[pastebin with complete log](http://pastebin.com/UcQtNGEd)
```
>stop
[00:13:30 INFO]: Stopping the server
[00:13:30 INFO]: Stopping server
[00:13:30 INFO]: [AutoIn] Disabling AutoIn v3.0-alpha.0
[00:13:30 ERROR]: Error occurred while disabling AutoIn v3.0-alpha.0 (Is it up to date?)
java.lang.NullPointerException 
	at nul.goto. ...\\.. .final..do.for(AutoIn_GotoFinal) ~[?:?]
	at com.gmail.bartlomiejkmazur.autoin.core.server.bukkit.AutoIn.onDisable(AutoIn_GotoFinal) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[spigot-1.8.jar:git-Spigot-b1e6da1-1092acb]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:359) [spigot-1.8.jar:git-Spigot-b1e6da1-1092acb]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [spigot-1.8.jar:git-Spigot-b1e6da1-1``092acb]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417) [spigot-1.8.jar:git-Spigot-b1e6da1-1092acb]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.disablePlugins(CraftServer.java:334) [spigot-1.8.jar:git-Spigot-b1e6da1-1092acb]
	at net.minecraft.server.v1_8_R1.MinecraftServer.stop(MinecraftServer.java:430) [spigot-1.8.jar:git-Spigot-b1e6da1-1092acb]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:561) [spigot-1.8.jar:git-Spigot-b1e6da1-1092acb]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]
```

**Java**
```
java -version
java version "1.7.0_75"
OpenJDK Runtime Environment (IcedTea 2.5.4) (7u75-2.5.4-1~deb7u1)
OpenJDK 64-Bit Server VM (build 24.75-b04, mixed mode)
```

**OS**
`Debian GNU/Linux 7 (wheezy)`

**Things i did**
1. Start the server
2. Add cracked user to whitelist
3. Log in with cracked user
4. Register (authme)
5. Log out
6. Log in with premium user (already registered)
7. Issued some help commands
8. Log out
9. Stop the server

**Comment by GotoFinal** [comment]
should be fixed in AutoIn-alpha.1, if not, open new issue.
