### ISSUE TITLE
BungeeCord crash at user login

### ISSUE THREAD

**Issue by MartinRM4** [GotoFinal/AutoIn#14]
Hi, 

when I try to connect to my server, I get the following error:

```
18:47:07 [SEVERE] [martinrm4] <-> InitialHandler - encountered exception
java.lang.NoSuchMethodError: net.md_5.bungee.EncryptionUtil.getCipher(ZLjavax/crypto/SecretKey;)Lnet/md_5/bungee/BungeeCipher;
    at nul.goto.?...\\.. .final..IIIIIIIlIl.handle(AutoIn_GotoFinal)
    at net.md_5.bungee.protocol.packet.EncryptionResponse.handle(EncryptionResponse.java:53)
    at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:75)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:182)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:182)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
    at java.lang.Thread.run(Thread.java:745)
```

----------------------------------------------
AutoIn configuration:
----------------------------------------------

```
Sockets: # If you want use this plugin with proxy server (BungeeCord) see: https://github.com/GotoFinal/AutoIn/wiki/Sockets
#- TYPE: LISTENER
#  Enabled: false
#  Host: localhost
#  Port: 22644
#  ServerName: serverOne
#  Required: true

- TYPE: HANDLER
  Enabled: true
  Port: 24444

# OPTIONS


Options:
  ConfigurationVersion_DO_NOT_CHANGE_THIS: 1
  UseChannels: false # DON'T USE THAT IF YOU CAN USE SOCKETS, Enable when you can't use sockets but you want use that on bungee server, it isn't good as sockets, but it should not explode. NOTE: You NEED MySQL for that, and this is slower and may by VERY buggy on first join.
  ReTryConnectSocketTime: 250 # Time in ms between trying connect LISTENER to HANLDER socket, on linux using smaller times can cause some weird problems.
  SaveData: # where AutoIn should store exceptions, enabled login, whitelists, cache and other player settings.
    Type: MySQL
    MySQL:
      Host: localhost
      Port: 3306
      User: xxxxxxx
      Pass: xxxxxxx
      Database: xxxxxx
      Prefix: "GT_"
    SQLite:
      File: "AutoIn_PlayerOptions.db"
```

<no changes to the default config file below this line> 

Bungeecord startup log:

```
18:43:41 [INFO] Using OpenSSL based native cipher.
18:43:41 [INFO] Using native code compressor
18:43:41 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.8-SNAPSHOT:"5699e86":1048
18:43:41 [INFO] Discovered module: ModuleSpec(name=cmd_alert, file=modules/cmd_alert.jar, provider=JenkinsModuleSource())
18:43:41 [INFO] Discovered module: ModuleSpec(name=cmd_find, file=modules/cmd_find.jar, provider=JenkinsModuleSource())
18:43:41 [INFO] Discovered module: ModuleSpec(name=cmd_list, file=modules/cmd_list.jar, provider=JenkinsModuleSource())
18:43:41 [INFO] Discovered module: ModuleSpec(name=cmd_send, file=modules/cmd_send.jar, provider=JenkinsModuleSource())
18:43:41 [INFO] Discovered module: ModuleSpec(name=cmd_server, file=modules/cmd_server.jar, provider=JenkinsModuleSource())
18:43:41 [INFO] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules/reconnect_yaml.jar, provider=JenkinsModuleSource())
18:43:41 [INFO] Loaded plugin cmd_alert version git:cmd_alert:1.8-SNAPSHOT:"5699e86":1048 by SpigotMC
18:43:41 [INFO] [AutoIn] Loading libraries from AutoIn/libs, remember: libs are only needed on some servers, and only with some enable                                                   d options.
18:43:41 [INFO] [AutoIn] Like SQLite is needed on BungeeCord only if you use SQLite database, but isn't needed on bukkit, bukkit conta                                                   ins own SQLite library.
18:43:41 [INFO] [AutoIn] Adding library to jvm: SQLite.jar
18:43:41 [INFO] [AutoIn] New socket handler at: 24444
18:43:41 [INFO] [AutoIn] Sockets enabled: [HANDLER:24444]
18:43:42 [INFO] Loaded plugin AutoIn version 3.0-pre.4 by GotoFinal
18:43:42 [INFO] Loaded plugin cmd_find version git:cmd_find:1.8-SNAPSHOT:"5699e86":1048 by SpigotMC
18:43:42 [INFO] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.8-SNAPSHOT:"5699e86":1048 by SpigotMC
18:43:42 [INFO] Loaded plugin cmd_send version git:cmd_send:1.8-SNAPSHOT:"5699e86":1048 by SpigotMC
18:43:42 [INFO] Loaded plugin cmd_server version git:cmd_server:1.8-SNAPSHOT:"5699e86":1048 by SpigotMC
18:43:42 [INFO] Loaded plugin cmd_list version git:cmd_list:1.8-SNAPSHOT:"5699e86":1048 by SpigotMC
18:43:42 [WARNING] Forced host server pvp is not defined
18:43:42 [INFO] Enabled plugin cmd_alert version git:cmd_alert:1.8-SNAPSHOT:"5699e86":1048 by SpigotMC
18:43:42 [INFO] [AutoIn] You have server protect enabled but you don't have any auth plugin! This option will not work...
18:43:42 [INFO] [AutoIn]
================================================================================

        AutoIn is now waiting for all required sockets to connect

  This is complete BETA version of plugin, if you see any bugs, report them!
  Don't make negative review because something don't work, it's BETA, just tell me that there is something wrong.

================================================================================
18:43:42 [INFO] [AutoIn]
================================================================================

  All required data loaded, plugin is now ready to use! Thanks for using it!
  If you need help, or you want help me (donations):
  http://www.spigotmc.org/resources/auto-in.578/

  This is complete BETA version of plugin, if you see any bugs, report them!
  Don't make negative review because something don't work, it's BETA, just tell me that there is something wrong.

================================================================================
18:43:42 [INFO] Enabled plugin AutoIn version 3.0-pre.4 by GotoFinal
18:43:42 [INFO] Enabled plugin cmd_find version git:cmd_find:1.8-SNAPSHOT:"5699e86":1048 by SpigotMC
18:43:42 [INFO] Enabled plugin reconnect_yaml version git:reconnect_yaml:1.8-SNAPSHOT:"5699e86":1048 by SpigotMC
18:43:42 [INFO] Enabled plugin cmd_send version git:cmd_send:1.8-SNAPSHOT:"5699e86":1048 by SpigotMC
18:43:42 [INFO] Enabled plugin cmd_server version git:cmd_server:1.8-SNAPSHOT:"5699e86":1048 by SpigotMC
18:43:42 [INFO] Enabled plugin cmd_list version git:cmd_list:1.8-SNAPSHOT:"5699e86":1048 by SpigotMC
18:43:42 [INFO] Listening on /0.0.0.0:25565
18:46:55 [INFO] [/xxx.xxx.57.130:27137] <-> InitialHandler has connected
18:46:57 [INFO] [/xxx.xxx.57.130:27585] <-> InitialHandler has connected
18:46:58 [INFO] [/xxx.xxx.57.130:27905] <-> InitialHandler has connected
```

... 
Error message follows here...
...

// Edited, use code syntax to paste errors/cfg, or just use pastebin next time.

**Comment by GotoFinal** [comment]
Hyym, seems that @md_5 changed one of method, this works on old bungee versions (like from month ago), after updating to newest my bungee also crashed.
That will be fixed in new release. 

And please... use code syntax or pastebin next time.

**Comment by GotoFinal** [comment]
Fixed in AutoIn-pre.5
