### ISSUE TITLE
All players kicked from bungeecord/bukkit server when an user disconnects

### ISSUE THREAD

**Issue by MartinRM4** [GotoFinal/AutoIn#15]
BungeeCord version: `git:BungeeCord-Bootstrap:1.8-SNAPSHOT:"5699e86":1048 by md_5`
Auto-In version: `Auto-In 3.0-pre.8`

### Problem description:
When any of the connected users disconnects, bugneecord server kicks out all players. 

### Scenario:
1. MartinRM4 connects (not shown in the log below)
2. FilipRM6 connects
3. FilipRM6 disconnects
4. MartinRM4 is kicked from the server (all other players in case they are logged to the server) with the following message:

```
22:05:42 [INFO] [FilipRM6] <-> [Auto-In]ServerConnector [lobby] has connected
22:05:51 [SEVERE] [FilipRM6] <-> DownstreamBridge <-> [lobby] - encountered exception
io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Cannot get ID for packet class net.md_5.bungee.protocol.packet.Kick
    at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:633)
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:691)
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:626)
    at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:944)
    at io.netty.channel.AbstractChannel.write(AbstractChannel.java:238)
    at net.md_5.bungee.netty.ChannelWrapper.write(ChannelWrapper.java:49)
    at net.md_5.bungee.ServerConnection$1.sendPacket(ServerConnection.java:36)
    at net.md_5.bungee.ServerConnection.disconnect(ServerConnection.java:58)
    at net.md_5.bungee.ServerConnection.disconnect(ServerConnection.java:49)
    at net.md_5.bungee.connection.UpstreamBridge.disconnected(UpstreamBridge.java:78)
    at net.md_5.bungee.netty.HandlerBoss.channelInactive(HandlerBoss.java:53)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:208)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:194)
    at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:247)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:208)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:194)
    at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:247)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:208)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:194)
    at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:208)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:194)
    at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
    at io.netty.handler.timeout.ReadTimeoutHandler.channelInactive(ReadTimeoutHandler.java:144)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:208)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:194)
    at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:828)
    at io.netty.channel.AbstractChannel$AbstractUnsafe$5.run(AbstractChannel.java:576)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Cannot get ID for packet class net.md_5.bungee.protocol.packet.Kick
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
    at net.md_5.bungee.protocol.Protocol$DirectionData.getId(Protocol.java:170)
    at net.md_5.bungee.protocol.MinecraftEncoder.encode(MinecraftEncoder.java:23)
    at net.md_5.bungee.protocol.MinecraftEncoder.encode(MinecraftEncoder.java:9)
    at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
    ... 32 more
22:05:51 [INFO] [FilipRM6] -> UpstreamBridge has disconnected
22:05:51 [INFO] [FilipRM6] <-> DownstreamBridge <-> [lobby] has disconnected
22:05:51 [INFO] [FilipRM6] <-> [Auto-In]ServerConnector [classic] has connected
22:05:51 [SEVERE] [martinrm4] -> UpstreamBridge - encountered exception
io.netty.handler.codec.EncoderException: java.lang.NullPointerException
    at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:633)
    at io.netty.channel.AbstractChannelHandlerContext.access$1900(AbstractChannelHandlerContext.java:32)
    at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:908)
    at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:893)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
    at net.md_5.bungee.protocol.DefinedPacket.writeString(DefinedPacket.java:18)
    at net.md_5.bungee.protocol.packet.PlayerListItem.write(PlayerListItem.java:94)
    at net.md_5.bungee.protocol.MinecraftEncoder.encode(MinecraftEncoder.java:24)
    at net.md_5.bungee.protocol.MinecraftEncoder.encode(MinecraftEncoder.java:9)
    at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
    ... 8 more
22:05:51 [INFO] [martinrm4] disconnected with: EncoderException : java.lang.NullPointerException @ io.netty.handler.codec.MessageToByteEncoder:125
22:05:51 [SEVERE] [martinrm4] <-> DownstreamBridge <-> [lobby] - encountered exception
io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Cannot get ID for packet class net.md_5.bungee.protocol.packet.Kick
    at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:633)
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:691)
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:626)
    at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:944)
    at io.netty.channel.AbstractChannel.write(AbstractChannel.java:238)
    at net.md_5.bungee.netty.ChannelWrapper.write(ChannelWrapper.java:49)
    at net.md_5.bungee.ServerConnection$1.sendPacket(ServerConnection.java:36)
    at net.md_5.bungee.ServerConnection.disconnect(ServerConnection.java:58)
    at net.md_5.bungee.ServerConnection.disconnect(ServerConnection.java:49)
    at net.md_5.bungee.UserConnection.disconnect0(UserConnection.java:348)
    at net.md_5.bungee.UserConnection.disconnect(UserConnection.java:306)
    at net.md_5.bungee.connection.UpstreamBridge.exception(UpstreamBridge.java:46)
    at net.md_5.bungee.netty.HandlerBoss.exceptionCaught(HandlerBoss.java:118)
    at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:246)
    at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:224)
    at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:79)
    at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:246)
    at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:224)
    at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:79)
    at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:246)
    at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:224)
    at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:79)
    at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:246)
    at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:224)
    at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:79)
    at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:246)
    at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:224)
    at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
    at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:246)
    at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:224)
    at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
    at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:246)
    at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:224)
    at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
    at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:246)
    at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:224)
    at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
    at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:246)
    at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:224)
    at io.netty.channel.DefaultChannelPipeline.fireExceptionCaught(DefaultChannelPipeline.java:834)
    at io.netty.channel.VoidChannelPromise.fireException(VoidChannelPromise.java:202)
    at io.netty.channel.VoidChannelPromise.tryFailure(VoidChannelPromise.java:163)
    at io.netty.channel.AbstractChannelHandlerContext.notifyOutboundHandlerException(AbstractChannelHandlerContext.java:720)
    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:635)
    at io.netty.channel.AbstractChannelHandlerContext.access$1900(AbstractChannelHandlerContext.java:32)
    at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:908)
    at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:893)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Cannot get ID for packet class net.md_5.bungee.protocol.packet.Kick
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
    at net.md_5.bungee.protocol.Protocol$DirectionData.getId(Protocol.java:170)
    at net.md_5.bungee.protocol.MinecraftEncoder.encode(MinecraftEncoder.java:23)
    at net.md_5.bungee.protocol.MinecraftEncoder.encode(MinecraftEncoder.java:9)
    at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
    ... 51 more
22:05:51 [INFO] [martinrm4] <-> DownstreamBridge <-> [lobby] has disconnected
22:05:51 [INFO] [martinrm4] -> UpstreamBridge has disconnected
22:05:51 [INFO] [martinrm4] <-> [Auto-In]ServerConnector [classic] has connected
22:06:21 [INFO] [FilipRM6] disconnected with: [Proxy] Lost connection to server.
22:06:21 [INFO] [FilipRM6] <-> DownstreamBridge <-> [classic] has disconnected
22:06:21 [INFO] [martinrm4] <-> DownstreamBridge <-> [classic] has disconnected
```

No messages appear on Lobby server. You are kicked from any server connected to the bungeecord, so I assume bungeecord is suspect in this case.

**Comment by GotoFinal** [comment]
`io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Cannot get ID for packet class net.md_5.bungee.protocol.packet.Kick` this don't look like error from AutoIn, there is no AutoIn class in any of errors. 

And, "bungeecord powered", what is that? o.o

**Comment by MartinRM4** [comment]
Hi,

sorry about the title. I wanted to say bungeecord powered bukkit farm.

About the log. I've catched some other log which contained AutoIn in the
output. Then I wanted to catch better log with defined reproduction
scenario and did not checked again that AutoIn messages are present.

Hold on, I'll check if I have the other logs still available.

Thx,


Martin M.

2015-02-27 19:46 GMT+01:00 GotoFinal <notifications@github.com>:

**Comment by MartinRM4** [comment]
One more comment. Look at issue #16. The exception message looks weird.
It's almost like something is overwriting memory - I know that's doable in
C/C++. Don't know if you can work similarly with dynamic memory allocation
in Java.

In case memory would be corrupt, a lot of strange things might happen
seamingly without relation to AutoIn... Surely, something else could cause
the damage, but I am not using any other bungeecord plugins than AutoIn. So
it's either the plugin, or bungeecord itself.


Martin M.

2015-02-27 20:41 GMT+01:00 Jayden Welborn <martin.r.matousek@gmail.com>:

**Comment by GotoFinal** [comment]
I currently rewriting whole network system in AutoIn, to use some more stable library.
So you will must wait for new version. (because that errors can be related to sockets)

But this error is really weird...
It is always? or only some time after server start?

**Comment by MartinRM4** [comment]
Look, the log complains about DownstreamBridge exception. I guess it's connection you are creating in AutoIn for connection between bungeecord and bukkit server (lobby in my case here).

```
00:12:26 [INFO] [martinrm4] disconnected with: EncoderException : java.lang.NullPointerException @ io.netty.handler.codec.MessageToByteEncoder:125
00:12:26 [SEVERE] [martinrm4] <-> DownstreamBridge <-> [lobby] - encountered exception
io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Cannot get ID for packet class net.md_5.bungee.protocol.packet.Kick
    at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:633)
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:691)
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:626)
    at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:944)
    at io.netty.channel.AbstractChannel.write(AbstractChannel.java:238)
    at net.md_5.bungee.netty.ChannelWrapper.write(ChannelWrapper.java:49)
    at net.md_5.bungee.ServerConnection$1.sendPacket(ServerConnection.java:36)
    at net.md_5.bungee.ServerConnection.disconnect(ServerConnection.java:58)
    at net.md_5.bungee.ServerConnection.disconnect(ServerConnection.java:49)
    at net.md_5.bungee.UserConnection.disconnect0(UserConnection.java:348)
    at net.md_5.bungee.UserConnection.disconnect(UserConnection.java:306)
    at net.md_5.bungee.connection.UpstreamBridge.exception(UpstreamBridge.java:46)
    at net.md_5.bungee.netty.HandlerBoss.exceptionCaught(HandlerBoss.java:118)
    at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:246)
    at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:224)
    at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:79)
    at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:246)
    at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:224)
    at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:79)
    at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:246)
    at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:224)
    at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:79)
    at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:246)
    at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:224)
    at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:79)
    at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:246)
    at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:224)
    at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
    at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:246)
    at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:224)
    at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
    at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:246)
    at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:224)
    at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
    at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:246)
    at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:224)
    at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
    at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:246)
    at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:224)
    at io.netty.channel.DefaultChannelPipeline.fireExceptionCaught(DefaultChannelPipeline.java:834)
    at io.netty.channel.VoidChannelPromise.fireException(VoidChannelPromise.java:202)
    at io.netty.channel.VoidChannelPromise.tryFailure(VoidChannelPromise.java:163)
    at io.netty.channel.AbstractChannelHandlerContext.notifyOutboundHandlerException(AbstractChannelHandlerContext.java:720)
    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:635)
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:691)
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:626)
    at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:944)
    at io.netty.channel.AbstractChannel.write(AbstractChannel.java:238)
    at net.md_5.bungee.netty.ChannelWrapper.write(ChannelWrapper.java:49)
    at net.md_5.bungee.UserConnection$1.sendPacket(UserConnection.java:138)
    at net.md_5.bungee.connection.UpstreamBridge.disconnected(UpstreamBridge.java:76)
    at net.md_5.bungee.netty.HandlerBoss.channelInactive(HandlerBoss.java:53)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:208)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:194)
    at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:247)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:208)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:194)
    at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:247)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:208)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:194)
    at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:208)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:194)
    at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
    at io.netty.handler.timeout.ReadTimeoutHandler.channelInactive(ReadTimeoutHandler.java:144)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:208)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:194)
    at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:828)
    at io.netty.channel.AbstractChannel$AbstractUnsafe$5.run(AbstractChannel.java:576)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Cannot get ID for packet class net.md_5.bungee.protocol.packet.Kick
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
    at net.md_5.bungee.protocol.Protocol$DirectionData.getId(Protocol.java:170)
    at net.md_5.bungee.protocol.MinecraftEncoder.encode(MinecraftEncoder.java:23)
    at net.md_5.bungee.protocol.MinecraftEncoder.encode(MinecraftEncoder.java:9)
    at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
    ... 73 more
00:12:26 [SEVERE] [FilipRM6] <-> DownstreamBridge <-> [lobby] - encountered exception
io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Cannot get ID for packet class net.md_5.bungee.protocol.packet.Kick
    at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:633)
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:691)
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:626)
    at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:944)
    at io.netty.channel.AbstractChannel.write(AbstractChannel.java:238)
    at net.md_5.bungee.netty.ChannelWrapper.write(ChannelWrapper.java:49)
    at net.md_5.bungee.ServerConnection$1.sendPacket(ServerConnection.java:36)
    at net.md_5.bungee.ServerConnection.disconnect(ServerConnection.java:58)
    at net.md_5.bungee.ServerConnection.disconnect(ServerConnection.java:49)
    at net.md_5.bungee.connection.UpstreamBridge.disconnected(UpstreamBridge.java:78)
    at net.md_5.bungee.netty.HandlerBoss.channelInactive(HandlerBoss.java:53)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:208)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:194)
    at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:247)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:208)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:194)
    at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:247)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:208)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:194)
    at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:208)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:194)
    at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
    at io.netty.handler.timeout.ReadTimeoutHandler.channelInactive(ReadTimeoutHandler.java:144)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:208)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:194)
    at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:828)
    at io.netty.channel.AbstractChannel$AbstractUnsafe$5.run(AbstractChannel.java:576)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Cannot get ID for packet class net.md_5.bungee.protocol.packet.Kick
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
    at net.md_5.bungee.protocol.Protocol$DirectionData.getId(Protocol.java:170)
    at net.md_5.bungee.protocol.MinecraftEncoder.encode(MinecraftEncoder.java:23)
    at net.md_5.bungee.protocol.MinecraftEncoder.encode(MinecraftEncoder.java:9)
    at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
    ... 32 more
00:12:26 [INFO] [FilipRM6] -> UpstreamBridge has disconnected
00:12:26 [INFO] [martinrm4] <-> DownstreamBridge <-> [lobby] has disconnected
00:12:26 [INFO] [martinrm4] -> UpstreamBridge has disconnected
00:12:26 [INFO] [FilipRM6] <-> DownstreamBridge <-> [lobby] has disconnected
00:12:26 [INFO] [martinrm4] <-> [Auto-In]ServerConnector [classic] has connected
00:12:26 [INFO] [FilipRM6] <-> [Auto-In]ServerConnector [classic] has connected
00:12:56 [INFO] [martinrm4] <-> DownstreamBridge <-> [classic] has disconnected
```

I have tried to restart the OS, but it did not helped. I will be researching it a bit more and wait for the new version you are mentioning in meanwhile. 

Do you plan this change still for 3.0 version, or you plan it for future versions only? Thx.

**Comment by GotoFinal** [comment]
yes, update will be still on 3.0 version, IDK when, maybe even in this week, but it's bigger change, so it can take some more time.

**Comment by GotoFinal** [comment]
open new issue if this is still a problem in AutoIn-alpha.1
