### ISSUE TITLE
Mojang premium account rejected by Auto-In

### ISSUE THREAD

**Issue by MartinRM4** [GotoFinal/AutoIn#16]
Bungeecord version: `git:BungeeCord-Bootstrap:1.8-SNAPSHOT:"5699e86":1048 by md_5`
Auto-In version: `3.0-pre.8`

1. User with premium Mojang account tries to connect to bungeecord server.
2. User is rejected by a message Connection Lost message:

```
Exception Connection:RuntimeException : Server is online mode! -> This mean that your AutoIn don't work <3 @ nul.goto. ...\ \..final,,IIIIIIIlIl:-1
```

3. The following message shows on bungeecord console:

```
21:54:03 [INFO] [FilipRM6] <-> [Auto-In]ServerConnector [lobby] has connected
21:54:03 [SEVERE] [FilipRM6] <-> [Auto-In]ServerConnector [lobby] - encountered exception
java.lang.RuntimeException: Server is online mode! -> This mean that your AutoIn don't work <3
    at nul.goto.?...\\.. .final..IIIIIIIlIl.handle(AutoIn_GotoFinal)
    at net.md_5.bungee.protocol.packet.EncryptionRequest.handle(EncryptionRequest.java:56)
    at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:75)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:182)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:182)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
    at java.lang.Thread.run(Thread.java:745)
21:54:03 [INFO] [FilipRM6] disconnected with: Exception Connecting:RuntimeException : Server is online mode! -> This mean that your AutoIn don't work <3 @ nul.goto.?...\\.. .final..IIIIIIIlIl:-1
21:54:03 [INFO] [FilipRM6] <-> [Auto-In]ServerConnector [lobby] has disconnected
21:54:03 [INFO] [FilipRM6] -> UpstreamBridge has disconnected
```
Cracked accounts can connect. Both Bungeecord and Lobby servers are configured `online_mode: false`.

Premium account users can normally connect after bungeecord server and lobby server restart. I don't know how to get bungeecord into this state, but it does not necessary need long time to happen.

**Comment by GotoFinal** [comment]
open new issue if this is still a problem in AutoIn-alpha.1
