### ISSUE TITLE
Error logging

### ISSUE THREAD

**Issue by FejminTV** [GotoFinal/AutoIn#4]
[13:26:24 ERROR]: Could not pass event PlayerJoinEvent to AutoIn v3.0-pre.2
net.minecraft.server.v1_8_R1.ReportedException: Sending packet
at net.minecraft.server.v1_8_R1.PlayerConnection.sendPacket(PlayerConnection.java:874) ~[spigot-1.8.jar:git-Spigot-d0d1d87-15e81cf]
at org.bukkit.craftbukkit.v1_8_R1.entity.CraftPlayer$1.sendMessage(CraftPlayer.java:1444) ~[spigot-1.8.jar:git-Spigot-d0d1d87-15e81cf]
at org.bukkit.craftbukkit.v1_8_R1.entity.CraftPlayer$1.sendMessage(CraftPlayer.java:1435) ~[spigot-1.8.jar:git-Spigot-d0d1d87-15e81cf]
at .goto.?.. .final..IIIIIlIlIl.abstract(Unknown Source) ~[?:?]
at .goto.?.. .final..IIIlIIlIll.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.jar:git-Spigot-d0d1d87-15e81cf]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.jar:git-Spigot-d0d1d87-15e81cf]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.jar:git-Spigot-d0d1d87-15e81cf]
at net.minecraft.server.v1_8_R1.PlayerList.onPlayerJoin(PlayerList.java:263) [spigot-1.8.jar:git-Spigot-d0d1d87-15e81cf]
at net.minecraft.server.v1_8_R1.PlayerList.a(PlayerList.java:148) [spigot-1.8.jar:git-Spigot-d0d1d87-15e81cf]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_71]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_71]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_71]
at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_71]
at .goto.?.. .final..IlIlllllIl.abstract(Unknown Source) [AutoIn.jar:?]
at .goto.?.. .final..IIIlIIlIII.abstract(Unknown Source) [AutoIn.jar:?]
at .goto.?.. .final..IIIIIlIlII.abstract(Unknown Source) [AutoIn.jar:?]
at .goto.?.. .final..IIIlIIlIlI.b(Unknown Source) [AutoIn.jar:?]
at net.minecraft.server.v1_8_R1.LoginListener.c(LoginListener.java:41) [spigot-1.8.jar:git-Spigot-d0d1d87-15e81cf]
at .goto.?.. .final..IIIlIIlIlI.c(Unknown Source) [AutoIn.jar:?]
at net.minecraft.server.v1_8_R1.NetworkManager.a(NetworkManager.java:159) [spigot-1.8.jar:git-Spigot-d0d1d87-15e81cf]
at net.minecraft.server.v1_8_R1.ServerConnection.c(ServerConnection.java:82) [spigot-1.8.jar:git-Spigot-d0d1d87-15e81cf]
at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:785) [spigot-1.8.jar:git-Spigot-d0d1d87-15e81cf]
at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot-1.8.jar:git-Spigot-d0d1d87-15e81cf]
at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot-1.8.jar:git-Spigot-d0d1d87-15e81cf]
at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot-1.8.jar:git-Spigot-d0d1d87-15e81cf]
at java.lang.Thread.run(Thread.java:745) [?:1.7.0_71]

**Comment by GotoFinal** [comment]
Check if error is still thrown on 3.0-pre.3 (it will be uploaded today)

**Comment by FejminTV** [comment]
An error occurred on the server is started, but after a reboot everything worked correctly

**Comment by GotoFinal** [comment]
So I will close it, make new issue if needed (with 3.0-pre.3 version)
