### ISSUE TITLE
Error Messages 

### ISSUE THREAD

**Issue by Berisko** [GotoFinal/AutoIn#65]
Hello, today I downloaded "AutoIn" plugin. I installed both "AutoIn" and "AutoInAuthMe". Started up a server got error messages in the console and can't do /autoin command.
I'm running Spigot 1.8.8 Server.

Console -
```
[09:46:30 WARN]: [AutoIn] Task #14 for AutoIn v3.0-alpha.5 generated an exception
java.lang.NoClassDefFoundError: fr/xephi/authme/api/NewAPI

at com.gotofinal.addon.autoin.authme.AuthMeModule.api(AuthMeModule.java:17) ~[?:?]

at com.gotofinal.addon.autoin.authme.AuthMeModule.getPlugin(AuthMeModule.java:59) ~[?:?]

at com.gotofinal.addon.autoin.authme.AuthMeModule.getPlugin(AuthMeModule.java:13) ~[?:?]

at com.gmail.bartlomiejkmazur.autoin.api.auth.BukkitLoginPlugin.getPluginName(AutoIn_GotoFinal) ~[?:?]

at com.gmail.bartlomiejkmazur.autoin.core.server.bukkit.BukkitAutoIn.for(AutoIn_GotoFinal) ~[?:?]

at nul.goto.Â ...\\.. .final..private.run(AutoIn_GotoFinal) ~[?:?]

at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[gbinvl_minecraft_spigot_1_8_8.jar:git-Spigot-6abac0c-9935adc]

at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [gbinvl_minecraft_spigot_1_8_8.jar:git-Spigot-6abac0c-9935adc]

at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:722) [gbinvl_minecraft_spigot_1_8_8.jar:git-Spigot-6abac0c-9935adc]

at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [gbinvl_minecraft_spigot_1_8_8.jar:git-Spigot-6abac0c-9935adc]

at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [gbinvl_minecraft_spigot_1_8_8.jar:git-Spigot-6abac0c-9935adc]

at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [gbinvl_minecraft_spigot_1_8_8.jar:git-Spigot-6abac0c-9935adc]

at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]
Caused by: java.lang.ClassNotFoundException: fr.xephi.authme.api.NewAPI

at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_45-internal]

at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[gbinvl_minecraft_spigot_1_8_8.jar:git-Spigot-6abac0c-9935adc]

at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[gbinvl_minecraft_spigot_1_8_8.jar:git-Spigot-6abac0c-9935adc]

at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_45-internal]

at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_45-internal]
... 13 more
[09:46:30 INFO]: [NoCheatPlus] Added hook: AllViolations(NCP) [1.0].
[09:46:30 INFO]: [TitleManager] No update was found.
[09:46:30 INFO]: [AutoIn] 

================================================================================


  All required data loaded, plugin is now ready to use! Thanks for using it!
  If you need help, or you want help me (donations):

  http://www.spigotmc.org/resources/auto-in.578/


  This is complete BETA version of plugin, if you see any bugs, report them!

  Don't make negative review because something don't work, it's BETA, just tell me that there is something wrong.


================================================================================
```

Berisko.

**Comment by GotoFinal** [comment]
Autoinauthme is only needed if you use authme in version 5.x

**Comment by Berisko** [comment]
@GotoFinal Do I need to use latest "AuthMe" verstion with "AutoIn" plugin or "AutoIn" plugin doesn't require "AuthMe" plugin to use server safely in offline mode?

**Comment by GotoFinal** [comment]
@Berisko If you want use AuthMe in version 3.x, then just remove "Autoinauthme.jar", AutoIn supprot xAuth, AuthMe and LogIt by itself, but not AuthMe 5.x
